"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.getenv("SECRET_KEY", "dev-only-secret-key")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = os.getenv(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1"
).split(",")

def env(name: str, default=None, *, required: bool = False):
    value = os.getenv(name, default)

    if required and (value is None or value == ""):
        raise RuntimeError(f"Missing required environment variable: {name}")

    return value


def env_path(name: str, default: str) -> Path:
    value = env(name, default)
    path = Path(value)

    if path.is_absolute():
        return path

    return BASE_DIR / path

# CEMS local data
CEMS_DATA_ROOT = env_path("CEMS_DATA_ROOT", "data/cems")


# GeoServer
GEOSERVER_URL = env("GEOSERVER_URL", "http://localhost:8080/geoserver")
GEOSERVER_USER = env("GEOSERVER_USER", required=True)
GEOSERVER_PASSWORD = env("GEOSERVER_PASSWORD", required=True)

GEOSERVER_WORKSPACE = env("GEOSERVER_WORKSPACE", "cems")
GEOSERVER_DATASTORE = env("GEOSERVER_DATASTORE", "cems_postgis")


# PostGIS connection for ogr2ogr.
# This must be reachable from where the Django management command runs.
OGR_POSTGIS_HOST = env("OGR_POSTGIS_HOST", "localhost")
OGR_POSTGIS_PORT = env("OGR_POSTGIS_PORT", "5432")
OGR_POSTGIS_DB = env("OGR_POSTGIS_DB", required=True)
OGR_POSTGIS_USER = env("OGR_POSTGIS_USER", required=True)
OGR_POSTGIS_PASSWORD = env("OGR_POSTGIS_PASSWORD", required=True)

CEMS_OGR_PG_CONN = (
    "PG:"
    f"host={OGR_POSTGIS_HOST} "
    f"port={OGR_POSTGIS_PORT} "
    f"dbname={OGR_POSTGIS_DB} "
    f"user={OGR_POSTGIS_USER} "
    f"password={OGR_POSTGIS_PASSWORD}"
)


# PostGIS connection as seen from GeoServer.
# If GeoServer is in Docker, host is usually the Postgres service name.
GEOSERVER_POSTGIS = {
    "host": env("GEOSERVER_POSTGIS_HOST", "postgis"),
    "port": env("GEOSERVER_POSTGIS_PORT", "5432"),
    "database": env("GEOSERVER_POSTGIS_DB", required=True),
    "schema": env("GEOSERVER_POSTGIS_SCHEMA", "public"),
    "user": env("GEOSERVER_POSTGIS_USER", required=True),
    "password": env("GEOSERVER_POSTGIS_PASSWORD", required=True),
}
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Core Spatial & API Frameworks
    'django.contrib.gis', 
    'rest_framework',
    
    # Portfolio Applications
    'flood_pipeline.apps.FloodPipelineConfig',
    'proximity_alerts.apps.ProximityAlertsConfig',
    'quality_dashboard.apps.QualityDashboardConfig',
    'vector_tiles.apps.VectorTilesConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": os.getenv("DATABASE_NAME"),
        "USER": os.getenv("DATABASE_USER"),
        "PASSWORD": os.getenv("DATABASE_PASSWORD"),
        "HOST": os.getenv("DATABASE_HOST", "localhost"),
        "PORT": os.getenv("DATABASE_PORT", "5432"),
    }
}

CEMS_RAPID_MAPPING_BASE_URL = os.getenv(
    "CEMS_RAPID_MAPPING_BASE_URL",
    "https://rapidmapping.emergency.copernicus.eu",
)
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
