# Generated by Django 5.2.9 on 2026-07-12 12:23

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CEMSRActivation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=20, unique=True)),
                ("name", models.CharField(max_length=500)),
                ("reason", models.TextField(blank=True, null=True)),
                ("countries", models.JSONField(default=list)),
                ("continent", models.CharField(blank=True, max_length=500, null=True)),
                ("category", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "sub_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("activation_time", models.DateTimeField(blank=True, null=True)),
                ("event_time", models.DateTimeField(blank=True, null=True)),
                ("registration_time", models.DateTimeField(blank=True, null=True)),
                ("publication_date", models.DateTimeField(blank=True, null=True)),
                (
                    "centroid",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("closed", models.BooleanField(default=False)),
                ("infobulletins", models.JSONField(blank=True, default=list)),
                (
                    "products_path",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "related_events",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "report_link",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
            ],
            options={
                "verbose_name": "CEMS activation",
                "verbose_name_plural": "CEMS activations",
                "ordering": ["-activation_time", "code"],
            },
        ),
        migrations.CreateModel(
            name="CEMSRAOI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aoi_number", models.PositiveIntegerField()),
                ("aoi_name", models.CharField(max_length=255)),
                ("is_real_extent", models.BooleanField(default=True)),
                (
                    "sqkm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("blp_path", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "activation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aois",
                        to="proximity_alerts.cemsractivation",
                    ),
                ),
            ],
            options={
                "ordering": ["activation__code", "aoi_number"],
            },
        ),
        migrations.CreateModel(
            name="CEMSRProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "product_acronym",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("monitoring", models.BooleanField(default=False)),
                (
                    "monitoring_number",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("feasible", models.BooleanField(default=True)),
                (
                    "extent",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("expected_delivery", models.DateTimeField(blank=True, null=True)),
                (
                    "download_path",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("stats_raw", models.JSONField(blank=True, default=dict)),
                (
                    "aoi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="proximity_alerts.cemsraoi",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "aoi__activation__code",
                    "aoi__aoi_number",
                    "product_type",
                ],
            },
        ),
        migrations.CreateModel(
            name="CEMSRProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(unique=True)),
                ("is_new", models.BooleanField(default=False)),
                ("resolution_class", models.CharField(max_length=100)),
                ("sensor_type", models.CharField(max_length=100)),
                (
                    "sensor_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("acquisition_time", models.DateTimeField(blank=True, null=True)),
                ("file_name", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="proximity_alerts.cemsrproduct",
                    ),
                ),
            ],
            options={
                "ordering": ["-acquisition_time", "sensor_name"],
            },
        ),
        migrations.CreateModel(
            name="CEMSRProductLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("layer_type", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "layer_json_path",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "layer_format",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "layer_sld_path",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layers",
                        to="proximity_alerts.cemsrproduct",
                    ),
                ),
            ],
            options={
                "ordering": ["product", "name"],
            },
        ),
        migrations.CreateModel(
            name="CEMSRProductStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("theme", models.CharField(max_length=255)),
                ("label", models.CharField(max_length=500)),
                ("unit", models.CharField(blank=True, max_length=50, null=True)),
                ("total", models.CharField(blank=True, max_length=100, null=True)),
                ("affected", models.CharField(blank=True, max_length=100, null=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="proximity_alerts.cemsrproduct",
                    ),
                ),
            ],
            options={
                "ordering": ["product", "theme", "label"],
            },
        ),
        migrations.CreateModel(
            name="CEMSRProductVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(null=True, unique=True)),
                (
                    "status_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("W", "Waiting for data"),
                            ("I", "In production"),
                            ("F", "Production finished"),
                            ("N", "Not produced"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                ("number", models.PositiveIntegerField(blank=True, null=True)),
                ("delivery_time", models.DateTimeField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="proximity_alerts.cemsrproduct",
                    ),
                ),
            ],
            options={
                "ordering": ["product", "number"],
            },
        ),
        migrations.AddConstraint(
            model_name="cemsraoi",
            constraint=models.UniqueConstraint(
                fields=("activation", "aoi_number"),
                name="unique_aoi_number_per_activation",
            ),
        ),
        migrations.AddConstraint(
            model_name="cemsrproductstat",
            constraint=models.UniqueConstraint(
                fields=("product", "theme", "label"),
                name="unique_product_stat_theme_label",
            ),
        ),
    ]
