# Generated by Django 5.2.9 on 2026-06-28 10:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CEMSRActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('reason', models.TextField(blank=True, null=True)),
                ('countries', models.JSONField(default=list)),
                ('continent', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(blank=True, max_length=500, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=100, null=True)),
                ('activation_time', models.DateTimeField(blank=True, null=True)),
                ('event_time', models.DateTimeField(blank=True, null=True)),
                ('registration_time', models.DateTimeField(blank=True, null=True)),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('extent', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('closed', models.BooleanField(default=False)),
                ('infobulletins', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
