# Generated by Django 5.2.9 on 2026-06-30 07:15

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proximity_alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cemsractivation',
            name='products_path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='CEMSAOI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aoi_number', models.PositiveIntegerField()),
                ('aoi_name', models.CharField(max_length=255)),
                ('blp_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aois', to='proximity_alerts.cemsractivation')),
            ],
        ),
    ]
