# Generated by Django 5.2.9 on 2026-06-30 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proximity_alerts', '0002_cemsractivation_products_path_cemsaoi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CEMSAOI',
            new_name='CEMSRAOI',
        ),
    ]
