# Generated by Django 5.2.9 on 2026-07-14 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proximity_alerts", "0002_cemsrgeoserverlayer"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommandLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("command_name", models.CharField(max_length=255)),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CEMSRGeoServerLayerGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("workspace", models.CharField(max_length=100)),
                ("group_name", models.CharField(max_length=255, unique=True)),
                ("is_published", models.BooleanField(default=False)),
                ("last_published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geoserver_layer_group",
                        to="proximity_alerts.cemsrproduct",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "product__aoi__activation__code",
                    "product__aoi__aoi_number",
                    "product__product_type",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace", "product"),
                        name="unique_geoserver_layer_group_per_product",
                    )
                ],
            },
        ),
    ]
