# Generated by Django 5.2.9 on 2026-07-01 17:12

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proximity_alerts', '0003_rename_cemsaoi_cemsraoi'),
    ]

    operations = [
        migrations.CreateModel(
            name='CEMRSProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(blank=True, max_length=100, null=True)),
                ('monitoring', models.BooleanField(default=False)),
                ('monitoring_number', models.PositiveIntegerField(blank=True, null=True)),
                ('feasible', models.BooleanField(default=True)),
                ('extent', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('expected_delivery', models.DateTimeField(blank=True, null=True)),
                ('aoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='proximity_alerts.cemsraoi')),
            ],
        ),
        migrations.CreateModel(
            name='CEMRSProductVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.CharField()),
                ('reason', models.TextField()),
                ('number', models.PositiveIntegerField()),
                ('delivery_time', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_version', to='proximity_alerts.cemrsproduct')),
            ],
        ),
        migrations.CreateModel(
            name='CEMSProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('is_new', models.BooleanField(default=False)),
                ('sensor_type', models.CharField(max_length=100)),
                ('resolution_class', models.CharField(max_length=100)),
                ('sensor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('acquisition_time', models.DateTimeField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=500, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='proximity_alerts.cemrsproduct')),
            ],
        ),
        migrations.CreateModel(
            name='CEMSRProductLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('brief_description', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='proximity_alerts.cemrsproduct')),
            ],
        ),
    ]
