# Generated by Django 5.2.9 on 2026-07-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proximity_alerts', '0004_cemrsproduct_cemrsproductversion_cemsproductimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cemrsproductversion',
            name='uuid',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
