# Generated by Django 5.2.9 on 2026-07-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proximity_alerts', '0005_cemrsproductversion_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cemsrproductlayer',
            name='brief_description',
        ),
        migrations.RemoveField(
            model_name='cemsrproductlayer',
            name='download_path',
        ),
        migrations.AddField(
            model_name='cemsrproductlayer',
            name='layer_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cemsrproductlayer',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
