# Generated by Django 5.2.9 on 2026-07-01 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proximity_alerts', '0006_remove_cemsrproductlayer_brief_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CEMRSProduct',
            new_name='CEMSRProduct',
        ),
        migrations.RenameModel(
            old_name='CEMSProductImage',
            new_name='CEMSRProductImage',
        ),
        migrations.RenameModel(
            old_name='CEMRSProductVersion',
            new_name='CEMSRProductVersion',
        ),
        migrations.AlterModelOptions(
            name='cemsractivation',
            options={'ordering': ['-activation_time', 'code'], 'verbose_name': 'CEMS activation', 'verbose_name_plural': 'CEMS activations'},
        ),
        migrations.AlterModelOptions(
            name='cemsraoi',
            options={'ordering': ['activation__code', 'aoi_number']},
        ),
        migrations.AlterModelOptions(
            name='cemsrproduct',
            options={'ordering': ['aoi__activation__code', 'aoi__aoi_number', 'product_type']},
        ),
        migrations.AlterModelOptions(
            name='cemsrproductimage',
            options={'ordering': ['-acquisition_time', 'sensor_name']},
        ),
        migrations.AlterModelOptions(
            name='cemsrproductlayer',
            options={'ordering': ['product', 'name']},
        ),
        migrations.AlterModelOptions(
            name='cemsrproductversion',
            options={'ordering': ['product', 'number']},
        ),
        migrations.RenameField(
            model_name='cemsraoi',
            old_name='code',
            new_name='activation',
        ),
        migrations.AlterField(
            model_name='cemsrproductversion',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_version', to='proximity_alerts.cemsrproductlayer'),
        ),
        migrations.AddConstraint(
            model_name='cemsraoi',
            constraint=models.UniqueConstraint(fields=('activation', 'aoi_number'), name='unique_aoi_number_per_activation'),
        ),
    ]
