# Generated by Django 5.2.9 on 2026-07-04 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proximity_alerts", "0007_rename_cemrsproduct_cemsrproduct_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cemsraoi",
            name="is_real_extent",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="cemsraoi",
            name="sqkm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="cemsrproduct",
            name="product_acronym",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cemsrproduct",
            name="product_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="cemsrproductversion",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_version",
                to="proximity_alerts.cemsrproduct",
            ),
        ),
    ]
