# Generated by Django 5.2.9 on 2026-07-04 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proximity_alerts", "0008_cemsraoi_is_real_extent_cemsraoi_sqkm_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cemsrproduct",
            name="product_name",
        ),
        migrations.AlterField(
            model_name="cemsrproductversion",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="proximity_alerts.cemsrproduct",
            ),
        ),
    ]
