# Generated by Django 5.2.9 on 2026-07-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proximity_alerts", "0009_remove_cemsrproduct_product_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cemsractivation",
            name="last_update",
        ),
        migrations.AlterField(
            model_name="cemsrproductversion",
            name="delivery_time",
            field=models.DateTimeField(null=True),
        ),
    ]
