# Generated by Django 5.2.9 on 2026-07-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proximity_alerts", "0010_remove_cemsractivation_last_update_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cemsrproduct",
            name="download_path",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
