# Generated by Django 5.2.9 on 2026-07-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proximity_alerts", "0011_cemsrproduct_download_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="cemsractivation",
            name="related_events",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
