# Generated by Django 5.2.9 on 2026-07-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proximity_alerts", "0012_cemsractivation_related_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="cemsrproductlayer",
            name="layer_format",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="cemsrproductlayer",
            name="layer_json_path",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="cemsrproductlayer",
            name="layer_sld_path",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
