# Generated by Django 5.2.9 on 2026-07-06 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proximity_alerts", "0013_cemsrproductlayer_layer_format_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cemsrproductversion",
            name="delivery_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cemsrproductversion",
            name="number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cemsrproductversion",
            name="reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cemsrproductversion",
            name="status_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="CEMSRGeoServerLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(default="impact_layer", max_length=100)),
                ("workspace", models.CharField(default="cemsr", max_length=255)),
                (
                    "datastore",
                    models.CharField(default="cemsr_postgis", max_length=255),
                ),
                ("table_name", models.CharField(max_length=255)),
                (
                    "geoserver_layer_name",
                    models.CharField(db_index=True, max_length=255),
                ),
                ("style_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "local_zip_path",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "local_shapefile_path",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "local_sld_path",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("is_downloaded", models.BooleanField(default=False)),
                ("is_imported_to_postgis", models.BooleanField(default=False)),
                ("is_published_to_geoserver", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geoserver_layers",
                        to="proximity_alerts.cemsrproduct",
                    ),
                ),
                (
                    "product_layer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="geoserver_layers",
                        to="proximity_alerts.cemsrproductlayer",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace", "geoserver_layer_name"),
                        name="unique_cems_geoserver_layer_name",
                    )
                ],
            },
        ),
    ]
