# Generated by Django 5.2.9 on 2026-07-06 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proximity_alerts", "0014_alter_cemsrproductversion_delivery_time_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CEMSRGeoServerLayer",
        ),
    ]
